version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000" # Next.js chạy trên port 3000
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000 # URL của backend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000" # Elysia chạy trên port 4000
    environment:
      DATABASE_URL: postgresql://postgres:bikinari1998@database:5432/Luckyboxweb
      REDIS_URL: redis://redis:6379
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./backend:/app
      - /app/node_modules

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bikinari1998
      POSTGRES_DB: Luckyboxweb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  db_data:
